- language: python
  python: 
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.5-dev"  # 3.5 development branch
    - "3.6"
    - "3.6-dev"  # 3.6 development branch
    - "3.7-dev"  # 3.7 development branch
  script:
    - python -m unittest discover

- os: linux
  language: c
  sudo: required
  dist: trusty
  before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3.7 python3.7-dev
  - python3 -m pip install cython
  install:
  - python3 -m cython stepbot.py -o stepbot.c
  - gcc `python3-config --cflags --ldflags` -o stepbot stepbot.c
  
- os: osx
  language: c
  before_install:
  - brew install python3
  - python3 -m pip install cython
  install:
  - python3 -m cython stepbot.py -o stepbot.c
  - sudo gcc `python3-config --cflags --ldflags` -I/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m -o stepbotmac stepbot.c